In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("owid-covid-data (1).csv")

In [ ]:
df.head()

## Selecting location as India

In [ ]:
df_India = df[df['location']=='India']
#df_India.info()

In [ ]:
df_India = df_India.dropna()

In [ ]:
#df_India.isnull().values.any()

In [ ]:
df_India.head()

In [ ]:
df_India['date'] = pd.to_datetime(df_India['date'])

In [ ]:
df_India.head()

In [ ]:
df_India = df_India.drop(['population'], axis=1)

In [ ]:
df_India = df_India.drop(['population_density'],axis=1)
df_India = df_India.drop(['median_age'],axis=1)
df_India = df_India.drop(['aged_65_older'],axis=1)
df_India = df_India.drop(['aged_70_older'],axis=1)
df_India = df_India.drop(['gdp_per_capita'],axis=1)
df_India = df_India.drop(['extreme_poverty'],axis=1)
df_India = df_India.drop(['cardiovasc_death_rate'],axis=1)
df_India = df_India.drop(['tests_units'],axis=1)
df_India = df_India.drop(['diabetes_prevalence'],axis=1)
df_India = df_India.drop(['female_smokers'],axis=1)
df_India = df_India.drop(['male_smokers'],axis=1)
df_India = df_India.drop(['handwashing_facilities'],axis=1)
df_India = df_India.drop(['hospital_beds_per_thousand'],axis=1)
df_India = df_India.drop(['life_expectancy'],axis=1)
df_India = df_India.drop(['human_development_index'],axis=1)


In [ ]:
df_India.corr()

## relplot

In [ ]:
sns.relplot(x="new_cases_smoothed", y="new_deaths_smoothed", data=df_India)

In [ ]:
sns.relplot(x="total_deaths",y="new_deaths",data=df_India)

In [ ]:
sns.relplot(x="positive_rate",y="new_tests_smoothed_per_thousand",data=df_India)

In [ ]:
sns.relplot(x="positive_rate",y="new_deaths",data=df_India)

In [ ]:
sns.relplot(x="total_cases",y="total_deaths",data=df_India)

In [ ]:
df_India=df_India.set_index('date')

## Single Value plots

### For Positive rate

In [ ]:
df_India['positive_rate'].plot(figsize=(14,6))

### For new_deaths_smoothed

In [ ]:
df_India['new_deaths_smoothed'].plot(figsize=(14,6))

### For new_tests_smoothed_per_thousand

In [ ]:
df_India['new_tests_smoothed_per_thousand'].plot(figsize=(14,6))

### For total_tests

In [ ]:
df_India['total_tests'].plot(figsize=(14,6))

### For stringency_index

In [ ]:
df_India['stringency_index'].plot(figsize=(14,6))

### Relplot

In [ ]:
sns.relplot(x="total_tests",y="positive_rate",data=df_India)

In [ ]:
sns.relplot(x="total_tests",y="total_deaths_per_million",data=df_India)

In [ ]:
#sns.pairplot(df_India)

In [ ]:
sns.relplot(x="total_tests",y="tests_per_case",data=df_India)

In [ ]:
df.columns

In [ ]:
keep_columns=['iso_code', 'continent', 'location', 'date', 'total_cases','total_deaths','new_deaths_smoothed','population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index']
df_use = df[keep_columns]
df_use['date'] = pd.to_datetime(df_use['date'])


In [ ]:
#df_use = df_use.set_index('date')

In [ ]:
df_use = df_use.dropna()

In [ ]:
df_use.info()

In [ ]:

df_use.continent.unique()

In [ ]:

Asia = df_use[df_use['continent']=='Asia']
Asia.location.unique()

In [ ]:
Asia.head()

In [ ]:
# Asia.median_age.unique()

In [ ]:
dates=[]
dates = list(Asia.date)

In [ ]:
#dates

In [ ]:
total_deaths1 = []
Armenia = Asia[Asia['location']=='Armenia']
Armenia = Armenia.dropna()
pop = Armenia.population.unique()
for total_deaths in Armenia.total_cases:
  total = total_deaths/pop[0]
  total_deaths1.append(total)
total_deaths2 = []
Nepal = Asia[Asia['location']=='Nepal']
Nepal = Nepal.dropna()
pop = Nepal.population.unique()
for total_deaths in Nepal.total_cases:
  total = total_deaths/pop[0]
  total_deaths2.append(total)
total_deaths3 = []
India = Asia[Asia['location']=='India']
India = India.dropna()
pop = India.population.unique()
for total_deaths in India.total_cases:
  total = total_deaths/pop[0]
  total_deaths3.append(total)
total_deaths4 = []
Pakistan = Asia[Asia['location']=='Pakistan']
Pakistan = Pakistan.dropna()
pop = Pakistan.population.unique()
for total_deaths in Pakistan.total_cases:
  total = total_deaths/pop[0]
  total_deaths4.append(total)
total_deaths5 = []
Thailand = Asia[Asia['location']=='Thailand']
Thaland = Thailand.dropna()
pop = Thailand.population.unique()
for total_deaths in Armenia.total_cases:
  total = total_deaths/pop[0]
  total_deaths5.append(total)
total_deaths6 = []
Vietnam = Asia[Asia['location']=='Vietnam']
Vietnam = Vietnam.dropna()
pop = Vietnam.population.unique()
for total_deaths in Armenia.total_cases:
  total = total_deaths/pop[0]
  total_deaths6.append(total)


In [ ]:
dataframe = list(zip(dates,total_deaths1,total_deaths2,total_deaths3,total_deaths4,total_deaths5,total_deaths6))

#### Total_cases/population for Countries Armenia, Nepal, India, Pakistan, Thailand, Vietnam

In [ ]:
df_Asia = pd.DataFrame(dataframe, columns = ['Date','Armenia', 'Nepal','India','Pakistan','Thailand','Vietnam']) 

In [ ]:
#sns.lineplot(data=flights_wide)
df_Asia.head()

#### Setting index as date

In [ ]:
df_Asia = df_Asia.set_index('Date')

In [ ]:
dims = (18,12)
fig, ax = plt.subplots(figsize=dims)
ax = sns.lineplot(ax=ax, data=df_Asia)
plt.setp(ax.get_legend().get_texts(), fontsize='20')
plt.setp(ax.get_legend().get_title(), fontsize='16')

In [ ]:
dims = (18,12)
fig, ax = plt.subplots(figsize=dims)
ax = sns.barplot(ax=ax, data=df_Asia)

In [ ]:
dates_new=[]
dates_new = list(Asia.date)
new_deaths1 = []
Armenia_new = Asia[Asia['location']=='Armenia']
Armenia = Armenia_new.dropna()
for new_deaths in Armenia.new_deaths_smoothed:
  new_deaths1.append(new_deaths)
new_deaths2 = []
Nepal_new = Asia[Asia['location']=='Nepal']
Nepal = Nepal_new.dropna()
for new_deaths in Nepal.new_deaths_smoothed:
  new_deaths2.append(new_deaths)
new_deaths3 = []
India = Asia[Asia['location']=='India']
India = India.dropna()
for new_deaths in India.new_deaths_smoothed:
  new_deaths3.append(new_deaths)
new_deaths4 = []
Pakistan = Asia[Asia['location']=='Pakistan']
Pakistan = Pakistan.dropna()
for new_deaths in Pakistan.new_deaths_smoothed:
  new_deaths4.append(new_deaths)
new_deaths5 = []
Thailand = Asia[Asia['location']=='Thailand']
Thaland = Thailand.dropna()
for new_deaths in Armenia.new_deaths_smoothed:
  new_deaths5.append(new_deaths)
new_deaths6 = []
Vietnam = Asia[Asia['location']=='Vietnam']
Vietnam = Vietnam.dropna()
for new_deaths in Vietnam.new_deaths_smoothed:
  new_deaths6.append(new_deaths)


In [ ]:
dataframe_new = list(zip(dates_new,new_deaths1,new_deaths2,new_deaths3,new_deaths4,new_deaths5,new_deaths6))

In [ ]:
df_Asia_new = pd.DataFrame(dataframe_new, columns = ['Date','Armenia', 'Nepal','India','Pakistan','Thailand','Vietnam']) 

In [ ]:
df_Asia_new = df_Asia_new.set_index('Date')

#### new_deaths_smoothed for Armenia, Nepal, India, Pakistan, Thailand, Vietnam

In [ ]:
dims = (18,12)
fig, ax = plt.subplots(figsize=dims)
ax = sns.barplot(ax=ax, data=df_Asia_new)

In [ ]:
Asia_sam = Asia[Asia['location'].isin(['Armenia','Nepal','India','Pakistan','Thailand','Vietnam'])]

In [ ]:
Asia_sam.location.unique()

#### percentage of people who are over 65 years for the above given countries in the above given order  

In [ ]:
Asia_sam.aged_65_older.unique()

#### percentage of male smokers for the above given countries in the above given order  

In [ ]:
Asia_sam.male_smokers.unique()

In [ ]:
##Asia_sam.female_smokers.unique()

#### cardiovascular death rate for the above given countries in the above given order  

In [ ]:
Asia_sam.cardiovasc_death_rate.unique()

#### percentage of people living in extreme poverty for the above given countries in the above given order  

In [ ]:
Asia_sam.extreme_poverty.unique()

In [ ]:
# Asia_sam[Asia_sam['location']=='Pakistan'].extreme_poverty.unique()

#### GDP per capita for the above given countries in the above given order  

In [ ]:
Asia_sam.gdp_per_capita.unique()

#### Number of hospital beds available per thousand people for the above given countries in the above given order  

In [56]:
Asia_sam.hospital_beds_per_thousand.unique()

array([4.2 , 0.53, 0.3 , 0.6 , 2.1 , 2.6 ])

#### Average life expectancy of a person living in these countries 

In [58]:
Asia_sam.life_expectancy.unique()

array([75.09, 69.66, 70.78, 67.27, 77.15, 75.4 ])

#### Human development Index of each country, Armenia and Thailand have the same HDI value

In [59]:
Asia_sam.human_development_index.unique()

array([0.755, 0.64 , 0.574, 0.562, 0.694])

In [66]:
#Asia_sam[Asia_sam['location']=='Pakistan'].human_development_index.unique()

In [67]:
#Asia_sam[Asia_sam['location']=='Nepal'].human_development_index.unique()

In [68]:
#Asia_sam[Asia_sam['location']=='India'].human_development_index.unique()

In [69]:
#Asia_sam[Asia_sam['location']=='Vietnam'].human_development_index.unique()

In [70]:
#Asia_sam[Asia_sam['location']=='Armenia'].human_development_index.unique()